### ISSUE TITLE
Solar return with house system other than default

### ISSUE THREAD

**Issue by bravenewcompany** [flatangle/flatlib#1]
We can create a chart using any house system, but it seems that solar return will always return chart using default house system, which is incorrect.

Maybe solar return should use self.hsys and self.IDs when creating solar return chart?

**Comment by joaoventura** [comment]
> Maybe solar return should use self.hsys and self.IDs when creating solar return chart?

You're right, at least it should reuse self.hsys while creating a new chart.

**Comment by joaoventura** [comment]
Fixed in 2c4f6289019d4cab806718fc5f3f7112d87dbf19
