### ISSUE TITLE
Does it have a swiss ephemeris DB?

### ISSUE THREAD

**Issue by chairperson-geo** [flatangle/flatlib#10]
Hello,
        This library has swiss ephemeris DB in it? if so how can i access it

**Comment by chairperson-geo** [comment]
Any replies to this request?

**Comment by joaoventura** [comment]
Yes, check this file: https://github.com/flatangle/flatlib/blob/master/flatlib/ephem/swe.py
But maybe you're interested in pyswisseph?

**Comment by Chistabo** [comment]
one must have pyswisseph installed on system, in virtual environment preferably.
it is mentionded somewhere in files, have not checked read.the.docs. 
EDIT: just checked 'installation' of docs, i have not found specific info that pyswisseph should be installed / available on target system.
this info should be added to docs.

s love nia
