### ISSUE TITLE
Splitting the output

### ISSUE THREAD

**Issue by chairperson-geo** [flatangle/flatlib#11]
>>> sun = chart.get(const.SUN)
>>> print(sun)
<Sun Pisces +22:47:25 +00:59:51>

In the above output, can i split and take Sun Pisces +22:47:25 +00:59:51 seperately? i am not able to do that as it does not have split method, any help?

**Comment by zebyja** [comment]
Looks to code, you can use functions:
chart.get(const.SUN).lon
chart.get(const.SUN).lat
chart.get(const.SUN).sign
chart.get(const.SUN).signlon
etc..
