### ISSUE TITLE
Midpoints

### ISSUE THREAD

**Issue by ElHombre87** [flatangle/flatlib#14]
Great tool but Midpoint calculations are essential. If it already exists how does one access it?

**Comment by joaoventura** [comment]
Hi, this library is mostly for traditional astrology, so I'm not planning on including midpoints for now.

**Comment by ElHombre87** [comment]
I understand, but to quote you:
    On Thursday, June 21, 2018, 6:17:33 PM CDT, João Ventura <notifications@github.com> wrote:  
 
 
Hi, this library is mostly for traditional astrology, so I'm not planning on including midpoints for now.

**Comment by ElHombre87** [comment]
To quote you:Why are you open-sourcing flatlib?I really want to help push forward data-driven research in astrology. That is only possible with a strong community of researchers and good tools, so there was no point in keeping flatlib hidden on my hard disk. Flatlib is also a good tool for talking about astrology techniques. Someone can always point to the source code to explain how things can be done.--------I believe, if you are really supporting data-driven research. The more data you offer, the better. Midpoints are easy enough to calculate, so it really isn't a necessity, but it would be a nice addition.I think limiting this tool with traditional astrology is a mistake. One should weigh the pro's and con's of doing so.Thank you for this tool though.
    On Thursday, June 21, 2018, 6:17:33 PM CDT, João Ventura <notifications@github.com> wrote:  
 
 
Hi, this library is mostly for traditional astrology, so I'm not planning on including midpoints for now.

**Comment by marekhewelt** [comment]
Hi @ElHombre87,

The code is in the open, well implemented and relatively easy to follow. Perhaps with investing a little bit of your time, you code it / fork it yourself?

Regards,
Marek
