### ISSUE TITLE
error on getting trans saturn planets

### ISSUE THREAD

**Issue by zebyja** [flatangle/flatlib#15]
Hello,

If i try chart.get(const.SUN) it works fine, but if i try consts.NEPTUNE (uran, pluto), it throws me error:

```
from flatlib import const
from flatlib.chart import Chart
from flatlib.datetime import Datetime
from flatlib.geopos import GeoPos

date = Datetime('1991/01/01', '10:00', '+02:00')
pos = GeoPos('40n50', '03e62')
chart = Chart(date, pos)
print(chart.get(const.NEPTUNE).num())
```

```
Traceback (most recent call last):
  File "/home/milan/PycharmProjects/elboh_astro/venv/test.py", line 9, in <module>
    print(chart.get(const.NEPTUNE).num())
  File "/home/milan/.local/lib/python3.5/site-packages/flatlib/chart.py", line 92, in get
    return self.getObject(ID)
  File "/home/milan/.local/lib/python3.5/site-packages/flatlib/chart.py", line 72, in getObject
    return self.objects.get(ID)
  File "/home/milan/.local/lib/python3.5/site-packages/flatlib/lists.py", line 44, in get
    return self.content[ID]
KeyError: 'Neptune'

Process finished with exit code 1
```

Please try it and tell me if its error on my side or You can reproduce it. I don't see error in git or swiss ephemeris library constants, but on my side also not.

thanks :o)

**Comment by marekhewelt** [comment]
Hello Zebyja,

I think when initiating the the chart object you need to set the list of objects you would like to use. The library, as configured bu default, uses traditional set of objects, see here in _chart.py_ lines 46,47 and 48:
`        # Handle optional arguments  `
`        hsys = kwargs.get('hsys', const.HOUSES_DEFAULT) `
`        IDs = kwargs.get('IDs', const.LIST_OBJECTS_TRADITIONAL) `

You would have to initiate your chart with `IDs = const.LIST_OBJECTS`

Regards,
Marek

**Comment by zebyja** [comment]
Hello Marek,

thank you very much, it looks really hope.

Regards
Zebyja
