### ISSUE TITLE
Equal houses

### ISSUE THREAD

**Issue by Chistabo** [flatangle/flatlib#16]
I have installed pyswisseph 2.05.01 (latest).
Using flatlib input:
    date = Datetime('2018/08/14', '12:00', '+01:00')
    pos = GeoPos('46n30', '16e14')  # Globoka, Slovenia, EU
    chart = Chart(date, pos, hsys='Equal')
I get output:
<House1 Scorpio +10:12:25 30.0>
<House2 Sagittarius +10:12:25 30.00000000000003>
<House3 Capricorn +10:12:25 30.0>
<House4 Aquarius +10:12:25 30.0>
<House5 Pisces +10:12:25 30.0>
<House6 Aries +10:12:25 30.0>
<House7 Taurus +10:12:25 30.0>
<House8 Gemini +10:12:25 30.0>
<House9 Cancer +10:12:25 30.0>
<House10 Leo +10:12:25 30.0>
<House11 Virgo +10:12:25 30.0>
<House12 Libra +10:12:25 29.99999999999997>

While error is nano size, it is still an erroneous output. Houses 2 & 12 are wrong size.

Simon
S love nia

**Comment by joaoventura** [comment]
Could you please check with the following change while building the chart?
`chart = Chart(date, pos, hsys=const.HOUSES_EQUAL)`

You need to refer to the house system using the constants defined in const.py..

**Comment by Chistabo** [comment]
Tried, as per Joao's instructions, ... hsys=const.HOUSES_EQUAL. Same result.

Simon
S love nia

**Comment by Chistabo** [comment]
Clicking 'Charts Web application' on flatangle.com gives attached
notification.

Lol, I see we have a same goal:
"his main interests is the use of computational tools for statistical
research in astrology"
Me too have idea to put astro calculations online. Also a research
database, etc. Perhaps you care for some coding help? But be warned, I am
programming beginner, and slow learner. Currently familiar with python,
django 2, html, bootstrap 4, and some c#, but it gave me trouble learning,
and I switched to python. Ufff, what a difference. :o

Unemployed for years, dedicated to astrology. First choice was indian
astrology, but open for western and other astrology branches as well. After
all, the planets are all the same.

Have fun,

Simon
S love nia
