### ISSUE TITLE
Does this hold good for indian astrology too ?

### ISSUE THREAD

**Issue by nileshdt** [flatangle/flatlib#17]

**Comment by joaoventura** [comment]
I'm not sure as I don't know much about indian astrology, but I guess there are lots of techniques here that belong mainly to traditional western astrology.

**Comment by Chistabo** [comment]
short answer: no
there is no dasas, naksatras, etc., jyotisa techniques.
for planets, you can add ayanamsa to calculated planets. this is how other software does jyotisa calculations.
ayanamsa(s) are available from pyswisseph module
