### ISSUE TITLE
Getting chart often raises math domain error

### ISSUE THREAD

**Issue by GoulartNogueira** [flatangle/flatlib#20]
Approximately 1/3 of my attempts results in this Math Domain Error:

> /opt/conda/lib/python3.6/site-packages/flatlib/utils.py in ascdiff(decl, lat)
>      16     delta = math.radians(decl)
>      17     phi = math.radians(lat)
> ---> 18     ad = math.asin(math.tan(delta) * math.tan(phi))
>      19     return math.degrees(ad)
> 
> ValueError: math domain error

For example, when I try with this parameters:

```
date = Datetime('1913/02/18', '22:15','+01:00')
pos = GeoPos('51n2149', '7e2754 ')

chart = Chart(date, pos)
```

Thanks in advance.
It's a really great lib and is helping me a lot!! :1st_place_medal:

**Comment by joaoventura** [comment]
Hi, you cannot use the lat/lon with 4 decimal numbers as you're doing in the example.
For instance, for 51n2149 you should either use 52n21:49 or 52n22. The same for the 7e2754..

It has to do with the functions to parse the lat/lon strings. They are not that well implemented.. 😃

**Comment by GoulartNogueira** [comment]
It was so simple! I feel stupid.
Thanks a lot, and congratulations for the open project.
It's helping me a lot!!!
