### ISSUE TITLE
how to properly use setTerms() with essential dignities

### ISSUE THREAD

**Issue by sstephans** [flatangle/flatlib#23]
code snippet

```
chart = Chart(date, pos, hsys=const.HOUSES_WHOLE_SIGN,IDs=const.LIST_OBJECTS)
sun = chart.getObject(const.SUN)
print(sun.sign)
print(sun.signlon)
essential.setTerms('LILLY_TERMS')
print(essential.TERMS)
print(essential.term(sun.sign, sun.signlon))
```

This is what I've been trying in order to use the lilly terms for the functions that come after it. I do not get any errors, but when it prints the terms table, it is still using the default egyptian terms. What's the proper way to set it to the other table of terms? Do I need to create some sort of object? 
Thanks

**Comment by joaoventura** [comment]
Use `essential.setTerms(essential.LILLY_TERMS)`
