### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by AlbusDum** [flatangle/flatlib#24]
Please help me to do with this problem when installin library
Windows 7, Python 3.6
![28-03-2019 20-42-09](https://user-images.githubusercontent.com/43916769/55180121-00199200-519a-11e9-8ad3-cd0ba943c30e.png)

**Comment by Chistabo** [comment]
windows 10
python37(4)
cmd - pip install flatlib

i get error, seems pyswisseph will not compile. pyswisseph is outdated (pip version of pyswisseph = 2.00.00, github version of pyswisseph = 2.05.01; sweph = version 2.08
i can not compile neither of them.
is flatlib development active?

simon
s love nia

**Comment by joaoventura** [comment]
Flatlib requires a version of pyswisseph>=2.00.00-2 (as in requirements.txt), so it should install the latest pyswisseph on pypi. However you can install the latest pyswisseph from github using `pip install git+https://github.com/astrorigin/pyswisseph`.

As for flatlib, I update it as I need it. I've been working actively in supporting the sidereal zodiac in another branch (https://github.com/flatangle/flatlib/tree/sidereal).
