### ISSUE TITLE
enable true node instead of mean node

### ISSUE THREAD

**Issue by sstephans** [flatangle/flatlib#25]
Is using the true node instead of the mean node an option in this library? I can't seem to find it as a setting. Thanks!

**Comment by sstephans** [comment]
If anyone is wondering, I figured it out. Unfortunately you have to edit one of the library files. But if you change the dictionary value for the north node const in ephem/swe.py from 10 to 11, it will give you true north and south nodes instead of mean nodes.

**Comment by starstruck77** [comment]
Hi, I changed the file in my directory, but it didn't help.  I still get the mean_node values.  I'm using Pycharm.  Wouldn't I need to reinstall flatlib as a custom package to make the changes work ? (I hope not as I couldn't figure out how to do that.....Thanks for some hints..
