### ISSUE TITLE
Objects (Pluto, Uranus, Neptune)

### ISSUE THREAD

**Issue by bonber** [flatangle/flatlib#27]
How i can get Pluto, Uranus, Neptune characteristics? There aren't in chart.objects. if i do a foreach the result is something like this:
`<Sun Cancer +14:20:30 +00:57:13>
<Moon Virgo +10:57:02 +11:55:50>
<Mercury Gemini +23:38:43 +01:18:18>
<Venus Leo +23:04:06 +01:09:29>
<Mars Taurus +28:25:18 +00:42:32>
<Jupiter Pisces +12:39:22 -00:00:53>
<Saturn Aquarius +09:49:07 -00:03:47>
<North Node Leo +10:06:52 -00:03:11>
<South Node Aquarius +10:06:52 -00:03:11>
<Syzygy Cancer +09:38:10 +13:04:03>
<Pars Fortuna Capricorn +09:40:49 +00:00:00>`

**Comment by lightflicker** [comment]
Hi Bonber,
You need to define which list of objects you want to use. See  _const.py_ and the example below:
`chart = Chart(<your datetime>, <your position>, IDs=const.LIST_OBJECTS)`
Regards,
Marek

**Comment by bonber** [comment]
I don't see that, thanks a lot i will try it
