### ISSUE TITLE
getObjectsinHouse() giving wrong objects

### ISSUE THREAD

**Issue by sstephans** [flatangle/flatlib#28]
Does this library rely on some external code. I had a program that previously worked and now when I try to calculate what house an object is in, it comes out incorrect. Asc and other angles are all correctly calculated, as are the objects. But for example I have a chart with pluto and jupiter in leo, and an asc at 15 virgo. No matter what I try, when I use the command for getting the objects in the first house, pluto and jupiter show up (in both placidus and whole sign). It's not limited to the first house tho. 

I've checked my code over and over and it seems there's something internal going wrong with the library and how it's spitting out objects in a house. In whole sign OR placidus there should be no way to have a virgo asc and have two objects in leo report being in first...

**Comment by sstephans** [comment]
ok I traced the problem to the internal logic of House.inhouse(). It must be incorrect. Anyway, for anyone who still wants to do house stuff with this library I wrote a couple helper functions for getting the what house an object is in. 

First you'll need one dictionary and one list (dictionary is for whole sign, list for quandrant house systems). 

```
if house_system == 'Whole Sign':
        houses = make_ws_houses(chart)
    else:
        houses = make_quadrant_houses(chart)
#make your data structures 
def make_ws_houses(chart):
    i = 1
    for house in chart.houses:
        self.houses_ws[house.sign] = i
        i += 1

def make_quadrant_houses(chart):
    houses = []
    for house in chart.houses:
        houses.append(house.lon)
    houses.append(houses[0])
    return houses

#get the house in which the object lives

if house_system == 'Whole Sign':
            house_of_object = houses[object.id]
else: #if quadrant houses
            house_of_object = get_house(object, chart)

def get_house(object, chart, houses):
    current = -1
    for i in range (0,12):
        if houses[i+1] - houses[i] < 0:
            if object.lon >= houses[i] and object.lon <= 360 or object.lon >= 0 and object.lon <= houses[i+1]:
                current = i+1
        if object.lon >= houses[i] and object.lon < houses[i+1]:
            current = i+1
    return current

```

it's a bit hackey but it works.

**Comment by Chistabo** [comment]
swe_houses indexing has changed from 
```
int swe_houses(
	double tjd_ut,	/* Julian day number, UT */
	...
	double* cusps,	/* array for 13 doubles */
	double* ascmc);	/* array for 10 doubles */
```
perhaps this could be the reason for false houses?

best regards,

simon
s love nia

**Comment by joaoventura** [comment]
As per traditional astrology rules, an object is considered to be in a house if it is at 5º or less degrees away from an house cusp. Did you consider that?

**Comment by sstephans** [comment]
Yes I did. The behavior was not that planets were ending up in the next house, but the previous one.

**Comment by sstephans** [comment]
Some planets are showing up in the wrong houses even in whole sign settings as well.

**Comment by marceloandriolli** [comment]
> ok I traced the problem to the internal logic of House.inhouse(). It must be incorrect. Anyway, for anyone who still wants to do house stuff with this library I wrote a couple helper functions for getting the what house an object is in.
> 
> First you'll need one dictionary and one list (dictionary is for whole sign, list for quandrant house systems).
> 
> ```
> if house_system == 'Whole Sign':
>         houses = make_ws_houses(chart)
>     else:
>         houses = make_quadrant_houses(chart)
> #make your data structures 
> def make_ws_houses(chart):
>     i = 1
>     for house in chart.houses:
>         self.houses_ws[house.sign] = i
>         i += 1
> 
> def make_quadrant_houses(chart):
>     houses = []
>     for house in chart.houses:
>         houses.append(house.lon)
>     houses.append(houses[0])
>     return houses
> 
> #get the house in which the object lives
> 
> if house_system == 'Whole Sign':
>             house_of_object = houses[object.id]
> else: #if quadrant houses
>             house_of_object = get_house(object, chart)
> 
> def get_house(object, chart, houses):
>     current = -1
>     for i in range (0,12):
>         if houses[i+1] - houses[i] < 0:
>             if object.lon >= houses[i] and object.lon <= 360 or object.lon >= 0 and object.lon <= houses[i+1]:
>                 current = i+1
>         if object.lon >= houses[i] and object.lon < houses[i+1]:
>             current = i+1
>     return current
> ```
> 
> it's a bit hackey but it works.
Where did you apply this helper?
Did you change the sources? There is a forked repo for these changes?

I asked because I had an issue with the angles of the house when I did the chart with `hsys=const.HOUSES_PLACIDUS`

**Comment by joaoventura** [comment]
It would be preferable to provide the data of the example that fails so that I could find the error in the source code..

**Comment by marceloandriolli** [comment]
> It would be preferable to provide the data of the example that fails so that I could find the error in the source code..

I did a mistake with hsys, now it work perfectly.

**Comment by joaoventura** [comment]
@marceloandriolli Sorry, I was basically replying to the original author of the thread..

**Comment by marceloandriolli** [comment]
> @marceloandriolli Sorry, I was basically replying to the original author of the thread..

Oh, okay! ha-ha-ha
