### ISSUE TITLE
How to draw a chart wheel with such as Matplotlib or other modules.

### ISSUE THREAD

**Issue by zgpnuaa** [flatangle/flatlib#29]
Hi,
    This module is great, it will be better to draw a astrology chart wheel.

**Comment by joaoventura** [comment]
Feature request is not an issue..

**Comment by zgpnuaa** [comment]
@joaoventura oh,sorry, i will pull a request about it ,thank you.

**Comment by zgpnuaa** [comment]
@joaoventura oh,sorry.
