### ISSUE TITLE
How to output data to astrochart.js

### ISSUE THREAD

**Issue by zgpnuaa** [flatangle/flatlib#30]
hello,
      I found a free and open-source [JavaScript library](https://github.com/Kibo/AstroChart) generating SVG charts to display planets in astrology. It's  in GitHub, which can draw astrology chart wheel。
      This js lib need input data in follow:
        	var data = {
				"planets":{"Lilith":[18], "Chiron":[18], "Pluto":[63], "Neptune":[110, 0.2], "Uranus":[318], "Saturn":[201, -0.2], "Jupiter":[192], "Mars":[210], "Moon":[268], "Sun":[281], "Mercury":[312], "Venus":[330], "NNode":[2]},
				"cusps":[296, 350, 30, 56, 75, 94, 116, 170, 210, 236, 255, 274]			
			};
     So how can i change such as :
<Sun Pisces +12:23:23 +01:00:11>
<Moon Taurus +06:45:04 +14:17:44>
<Mercury Pisces +08:41:45 +01:50:28>
<Venus Aries +13:05:45 +00:03:51>
<Mars Aries +24:45:31 +00:43:39>
<Jupiter Libra +22:12:31 -00:04:27>
<Saturn Sagittarius +26:49:41 +00:03:18>
<North Node Virgo +03:00:25 -00:03:11>
<South Node Pisces +03:00:25 -00:03:11>
<Syzygy Pisces +08:12:07 +13:36:06>
<Pars Fortuna Libra +28:49:54 +00:00:00>
   to the js lib example data format ?
   Thank you。

**Comment by joaoventura** [comment]
You can access the properties of the Python objects and export the data as you need them. You can check some examples at https://github.com/flatangle/flatlib/tree/master/recipes.

**Comment by joaoventura** [comment]
You can access the properties of the Python objects and export the data as you need them. You can check some examples at https://github.com/flatangle/flatlib/tree/master/recipes.

**Comment by zgpnuaa** [comment]
I got it.

It's wonderful.
Thank you.


---Original---
