### ISSUE TITLE
Planets aspects

### ISSUE THREAD

**Issue by marceloandriolli** [flatangle/flatlib#31]
Is there a way to get aspects like angles, degrees that involve two or more planets, for example, opposition angle 180°, square angle 90°,  trigone of angle 120° and conjunction?

**Comment by GoulartNogueira** [comment]
Marcelo, those aspects you mentioned are between 2 planets.
I understand your question. Geometrically an angle is defined by 3 points.
But astrologically, we consider ourselves as one point in the center of the chart, and compare the aspects between 2 other planets.

For example, if the sun is up high in the sky and the moon is rising in the horizon, they form a square angle 90º.

**Comment by marceloandriolli** [comment]
Thank you @GoulartNogueira!
But is there a way to get these aspects that a mentioned above?

I know that there is a method called getAspec, for example:

```
# Retrieve the Sun and Moon 
sun = chart.get(const.SUN)
moon = chart.get(const.MOON)

# Get the aspect
aspect = aspects.getAspect(sun, moon, const.MAJOR_ASPECTS)
print(aspect)
```

But I got this result: ```

Aspects:
<Moon Sun -1 None +00:00:00>
```

it sound weird!

**Comment by GoulartNogueira** [comment]
There is nothing weird in the result.
Your chart probably doesn't have any aspect between the Sun and the Moon. That's perfectly usual. 
I understand the code is working fine. 
I suggest you to study a little more about astrology before trying to understand the code and programming.
