### ISSUE TITLE
Lahiri Ayanamsa

### ISSUE THREAD

**Issue by indirakshee2001** [flatangle/flatlib#32]
How to apply various ayanamsa? 
For Example : <Sun Capricorn +17:31:21 +01:01:10> is as per the existing code, however applying the Ayanamsa it should be Sun in Sagittarius  23 Deg, 58',21''

is this possible?

**Comment by joaoventura** [comment]
I have a sideral branch that is working, but is very very unstable and incomplete (https://github.com/flatangle/flatlib/tree/sidereal). You can try to use it...
