### ISSUE TITLE
There is only Chiron in minor planets, but i didn't found Juno, Pallas, Ceres, Vesta.

### ISSUE THREAD

**Issue by zgpnuaa** [flatangle/flatlib#33]
In Traditional Astrology , there are 5 important minor planets. They are Chiron, Juno,  Pallas,  Ceres and Vesta. 
Juno is the zodiac sign of marriage and commitment.
Pallas is the zodiac sign of brain functions.
Ceres is the zodiac sign of depth of love that sits within all of us.
But  i didn't found Juno, Pallas, Ceres, Vesta in flatlib.
So its better to perfect the other four minor planets.
Thank you!

**Comment by joaoventura** [comment]
Minor planets are not used in Western Traditional Astrology.

**Comment by xAlstrat** [comment]
How can we include those minor planets? I've read the code and the constants are defined in swisseph but not in swe.py from flatlib.

I'm trying to figure out how to include those plantes, any idea?

Thanks.
