### ISSUE TITLE
Output to png, gif, jpeg?

### ISSUE THREAD

**Issue by StL-Jim** [flatangle/flatlib#34]
Hello,

Is there a way to output the results into a graphical chart such as a jpeg, gif or other graphical format?  If not do you have a suggestion on how to take the output and put it into a graphical chart?

--Jim

**Comment by Chistabo** [comment]
1) choose your favorite ui graphical library, ie pyqt5, or migw, etc. mine is bokeh, runs in web browser
2) get flatlib data, to be presented on chart
3) import and plot that data on chart, with ui library

have fun,

simon
s love nia
