### ISSUE TITLE
Sidereal astrology

### ISSUE THREAD

**Issue by Arthur-Cassarin-Grand** [flatangle/flatlib#35]
Hello,
I've been looking for a library as flatlib for months and I'm really enjoying the way you've done it ! Very impressive ! I've done some tests and found that you're using (to me) the tropical system. I would like to use the sidereal Lahiri ones. I would like to know if you can setup this kind of parameter in flatlib ?

Many thanks for your works !

**Comment by joaoventura** [comment]
Hi, I have a sideral astrology branch which is still quite unstable. You can try to use it and see if it works for you: https://github.com/flatangle/flatlib/tree/sidereal

**Comment by rajeevbharol** [comment]
> Hi, I have a sideral astrology branch which is still quite unstable. You can try to use it and see if it works for you: https://github.com/flatangle/flatlib/tree/sidereal

Thankyou. I see this comment is from 2020. Is this branch working well now?
