### ISSUE TITLE
True node vs. Mean Node

### ISSUE THREAD

**Issue by starstruck77** [flatangle/flatlib#36]
Hi, is there a way to calculate true_Node values ?  I have seen the closed issue that you need to change the library file, but it doesn't work for me. I have changed the file as described here: " But if you change the dictionary value for the north node const in ephem/swe.py from 10 to 11, it will give you true north and south nodes instead of mean nodes."   I am using Pycharm and it doesn't work. Anything else to do than to change the file ?  Thanks !

**Comment by Chistabo** [comment]
it is not clear what you mean with 'it doesn't work'. your code example, results?
generally, changing 'conts.NORTH_NODE' value to 11 should do the trick.
from swisseph (swephprg) documentation:
`
#define SE_MEAN_NODE  10 
#define SE_TRUE_NODE  11 
`
simon
s love nia

**Comment by xAlstrat** [comment]
I'm working with Pycharm too, and editing the file works ok. It's a issue not related to this library, this should works for any.

Be sure you are running your code in the same environment you edited.
