### ISSUE TITLE
changing pos = GeoPos('38n32', '8w54')

### ISSUE THREAD

**Issue by flipchan** [flatangle/flatlib#37]
how do i know the longitude and latidue current positions?

**Comment by flipchan** [comment]
is it the current long and lattitude of the earth that is suppose to use

**Comment by flipchan** [comment]
This is the lang and latitude of birthtown, plz add this to documentation

**Comment by Chistabo** [comment]
geoData usually refers to natal place of birth, or position of observer from earth in topocentric astrochart calculation.
generally, calculations are done geocentric(ally), from earth's center (as center of the sphere).

simon
s love nia
