### ISSUE TITLE
fixstar function update

### ISSUE THREAD

**Issue by aum7** [flatangle/flatlib#40]
olo,
thx for sharing this lib, useful, though limited (to west. trad. astro.).

quote from swisseph (ch) docs:
"For new projects, we recommend using the new functions swe_fixstar2_ut() and swe_fixstar2(). Performance will be a lot better  if a great number of fixed star calculations are done. "
with swisseph 2.07, new fixstar functions were added.
another quote :
"The  fixed  stars  functions  only  work  if  the  fixed  stars  data  file  sefstars.txt  is  found  in  the  ephemeris  path.  If the file sefstars.txt  is  not  found,  the  old  file  fixstars.cat  is  searched  and  used  instead,  if  present.  However,  it  is  strongly recommended to *not* use the old file anymore. The data in the file are outdated, and the algorithms are also not as accurate as those used with the file sefstars.txt. "

regarding this, comparing flatlib/const.py and sefstars.txt (recommended above), to use sefstars.txt, constants in const.py should be updated (i believe, if they are used to search fixstars.cat file):
# chi: from sefstars.txt: Zuben Eschamali
STAR_ZUBEN_ESCHAMALI = 'Zuben Eschamali'
# chi: from sefstars.txt: Rigel Kentaurus
STAR_RIGEL_KENTAURUS = 'Rigel Kentaurus'

so, sefstars.txt could be added to flatlib/resources/swefiles folder.

not sure if implementing (or completely substituting old) new swe_fixstar2() and swe_fixstar2_ut() makes any sense for this library.

pyswisseph has been updated to 2.08, recently. 

s love nia

**Comment by joaoventura** [comment]
This will be fixed in a new version that will be soon deployed..
