### ISSUE TITLE
Aspects of between  planets

### ISSUE THREAD

**Issue by marceloandriolli** [flatangle/flatlib#42]
Is there a way to get aspects a like Trine, Conjunction, Square ... between two planets beyond getAspects()?

**Comment by joaoventura** [comment]
Hi, if you need something more that what getAspects() gives you, you can always do something like subtract the longitudes of two objects and check which aspect is there. The script "aspects.py" (namely this function: https://github.com/flatangle/flatlib/blob/master/flatlib/aspects.py#L108) does a lot regarding aspects (aspect type, dexter vs sinister aspects, applicative vs separative aspects, etc.)

**Comment by ProgrammingLife** [comment]
@joaoventura, Could you please provide me with a little example on how to use getAspect() method for getting the angle in degrees between two planets at some date?

**Comment by andandio** [comment]
@ProgrammingLife You might look to aspectsByCat() in the ChartDynamics class to achieve that.

**Comment by joaoventura** [comment]
@ProgrammingLife, check the aspects example at the recipes directory (https://github.com/flatangle/flatlib/blob/master/recipes/aspects.py). The aspect object (https://github.com/flatangle/flatlib/blob/master/flatlib/aspects.py#L265) has a properties (such as orb and aspect type) that you can use.

But if you only want to find the angle between two objects, check the closestdistance function (https://github.com/flatangle/flatlib/blob/master/flatlib/angle.py#L48) and give it the zodiacal longitude of both planets (like sun.lon, moon.lon, etc., where sun and moon are Chart objects).
