### ISSUE TITLE
Issue After Installation

### ISSUE THREAD

**Issue by nikinpy** [flatangle/flatlib#45]
I installed flatlib using the new link provided recently.
I used this code to start to play around
from flatlib.datetime import Datetime
from flatlib.geopos import GeoPos
from flatlib.chart import Chart
date = Datetime('2018/04/18', '17:00', '+00:00')
pos = GeoPos('38n32', '8w54')
chart = Chart(date, pos)
moon = chart.get(const.MOON)
print(moon)

got this error.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-33a8b5248883> in <module>
      5 pos = GeoPos('38n32', '8w54')
      6 chart = Chart(date, pos)
----> 7 moon = chart.get(const.MOON)
      8 print(moon)

NameError: name 'const' is not defined

Will appreciate any help here.

**Comment by jakubruszkowski** [comment]
You have to import const:
`from flatlib import const`

**Comment by nikinpy** [comment]
Thanks, appreciate it.
