### ISSUE TITLE
Provide reference documentation.

### ISSUE THREAD

**Issue by ShadowJonathan** [flatangle/flatlib#48]
Update the currently 5 year old(!) documentation with reference documentation; documentation that shows the internals of the library in a readable way for everyone to see and reference from.

Example of such documentation: [discord.py](https://discordpy.readthedocs.io/en/latest/api.html)

Extra; Move scripts/examples/receipes to documentation website.

Extra; Remove (practically useless and redundant) tutorial on python itself. (Reasoning; the documentation needs to be library-specific, if anyone came here and didn't knew python, this library should not teach them, only provide a link to such a tutorial)

**Comment by ShadowJonathan** [comment]
(this is mostly an issue for myself to remind me later to do this work and submit a PR)

**Comment by joaoventura** [comment]
@ShadowJonathan, again thanks for your will to help. 

Please go ahead with the docs! 👍

**Comment by zdomjus60** [comment]
@joaoventura  @ShadowJonathan 
Flatlib is a very good library, but it lacks a good reference documentation. Simple remedy for all who are interested:
in your desktop or elsewhere open a terminal and write:
**pip3 install pdoc3** 
(if you have not installed it before)
**python3 -m pdoc --html flatlib**
a new html directory will be created, with a flatlib dir within it. Open index.html  and enjoy your new flatlib documentation

**Comment by zdomjus60** [comment]
To avoid the hassle of compiling, I have attached a zip file of the newly created reference documentation directory:

[flatlib.zip](https://github.com/flatangle/flatlib/files/5034778/flatlib.zip)
