### ISSUE TITLE
Move towards PEP8 naming convention, add typing

### ISSUE THREAD

**Issue by ShadowJonathan** [flatangle/flatlib#49]
Should this library be moving towards a more pep8-friendly naming convention?

For example, rename (`flatlib.ephem.swe.`)`lunarEclipseGlobal` to `lunar_eclipse_global`, and add `lunarEclipseGlobal = lunar_eclipse_global` for backwards compatibility.
(Note: probably also rename this function to `global_lunar_eclipse` for a more grammatically correct name, or move it under `.swe.eclipse.lunar(global=True)` or similar)

Also, this library would heavily benefit from type annotations (example: `def norm(angle: int) -> int:`) which provide duck-type hints for IDEs and other typechecking tools, and reduces potential bugs.

**Comment by ShadowJonathan** [comment]
Pinging @joaoventura, this issue is mostly also, like #48, a todo list item for myself to make a corresponding PR for later on, but also to receive feedback.

**Comment by joaoventura** [comment]
@ShadowJonathan, thanks for your will to update this library. 

Regarding lowercase with underscores, I still have to think about it. I use it on most of my current projects, but there's too many code already there, and already being used. Let me think about it, probably to a new version.

As for type annotations, I'm not a fan and I think it obfuscates some of the code. Let me also think about it..

**Comment by ShadowJonathan** [comment]
@joaoventura In that case, I was also planning to open a 3rd issue when I saw the lengthy `.const` file, with everything being thrown in as top-level names, and I thought that changing that to enums would clean up everything neatly into categories;
```py
# Sign figures
SIGN_FIGURE_NONE = "None"
SIGN_FIGURE_BEAST = "Beast"
SIGN_FIGURE_HUMAN = "Human"
SIGN_FIGURE_WILD = "Wild"

# Sign fertilities
SIGN_FERTILE = "Fertile"
SIGN_STERILE = "Sterile"
SIGN_MODERATELY_FERTILE = "Moderately Fertile"
SIGN_MODERATELY_STERILE = "Moderately Sterile"
```
to
```py
import enum

class SignFigure(enum.Enum):
    NONE = "None"
    BEAST = "Beast"
    HUMAN = "Human"
    WILD = "Wild"

class SignFertility(enum.Enum):
    FERTILE = "Fertile"
    STERILE = "Sterile"
    MOD_FERTILE = "Moderately Fertile"
    MOD_STERILE = "Moderately Sterile"
```
What're your thoughts on this as well?

**Comment by ShadowJonathan** [comment]
> As for type annotations, I'm not a fan and I think it obfuscates some of the code. Let me also think about it.

Type annotations' pros weigh out much more than adding more to the code, explicit > implicit, if i look at `flatlib.angles.norm`, and i look at the input variables, i have no idea if whatever comes in there is an `int`, a `float`, or a `Decimal`, because it's not annotated, and almost nothing else in the library is. This means that the IDE and the developer would mostly be working in the dark when working on and with this library, being without references and reasonably-assured typing with each variable.

Sorry if I come over as aggressive or pushy, but I think that type annotations have much more benefits than it might seem like at first glance, and in my personal opinion, it doesn't obfuscate, but rather clarifies most of it.

**Comment by ShadowJonathan** [comment]
If putting typing inside the code files is an issue for obfuscation, it's also possible to put them inside specific `.pyi` stub files which go alongside the actual code files.

**Comment by joaoventura** [comment]
I think this doesn't bring much benefit for now..

**Comment by joaoventura** [comment]
Will close this for now..
