### ISSUE TITLE
Tuple index out of range

### ISSUE THREAD

**Issue by dxcore35** [flatangle/flatlib#53]
**System:** Mac OS. Python 3.7
**Installation via**: `pip3 install git+https://github.com/flatangle/flatlib`
**Pyswisseph version**: 2.00.00-2

Error come when using example code from description.

```
/usr/local/lib/python3.7/site-packages/flatlib/ephem/swe.py in sweObject(obj, jd)
     69         'lon': sweList[0],
     70         'lat': sweList[1],
---> 71         'lonspeed': sweList[3],
     72         'latspeed': sweList[4]
     73     }

IndexError: tuple index out of range
```

**Comment by zgpnuaa** [comment]
So have you solve this error?
i have same errors in win10, because i install pyswisseph==2.8.0-post, and only can install  pyswisseph==2.8.0-post  in win10 ,
so maybe pyswisseph have some new chanages.

**Comment by dxcore35** [comment]
Oh sorry I thought I closed this.
Yes, after uninstallation via pip and installation again it works now!
