### ISSUE TITLE
pluto is not in the chart

### ISSUE THREAD

**Issue by rxng** [flatangle/flatlib#59]
Pluto is referenced in the code, but it does not appear in the chart

**Comment by joaoventura** [comment]
Did you set the IDs on the Chart constructor to include Pluto?
Check the Chart constructor method at https://github.com/flatangle/flatlib/blob/master/flatlib/chart.py#L48
and the list of planets that include Pluto at https://github.com/flatangle/flatlib/blob/master/flatlib/const.py#L264
By default, the Chart constructor method uses the list of traditional astrology objects which does not include Pluto..

**Comment by rxng** [comment]
Thanks this works!!
