### ISSUE TITLE
Moon sign returning wrong one from other tools

### ISSUE THREAD

**Issue by rxng** [flatangle/flatlib#60]
99% of the calculations are correct, however, 
26/12/1979 1am - Melbourne 

flatlib returns moon sign as Aries,
other tools (including Keryion, and online sites) are returning Pisces

I figured out - Flatlib does not take into account the timezone when passing GeoPos longitude and latitude. Surely there must be some way than to figure out the utc manually each time?

**Comment by joaoventura** [comment]
There's pytz which people can use to find the timezone offset from UTC. This library requires correct inputs from the programmers..
