### ISSUE TITLE
Iterate for two years? 

### ISSUE THREAD

**Issue by srinu88558** [flatangle/flatlib#63]
Please help me to iterate for two years
from 
Datetime('2015/03/13', '17:00', '+00:00')
To
Datetime('2017/03/13', '17:00', '+00:00') 
for the following below code:
>>> date = Datetime('2015/03/13', '17:00', '+00:00')
>>> pos = GeoPos('38n32', '8w54')
>>> chart = Chart(date, pos)

>>> sun = chart.get(const.SUN)
>>> print(sun)
<Sun Pisces +22:47:25 +00:59:51>

**Comment by joaoventura** [comment]
Github issues are for stating errors or similar things, not for asking for free work...
