### ISSUE TITLE
cannot install, fails at pyswisseph

### ISSUE THREAD

**Issue by annebancroftsghost** [flatangle/flatlib#65]
I haven't been able to install this module, it fails when it tries to install the pyswisseph dependency. I've been able to manually install the pyswisseph wheel, but the installer for flatlib still tries to uninstall and reinstall it, causing it to still fail. What's the solution?

**Comment by aum7** [comment]
same here, the error is

`cannot open include file: 'wtypes.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2`

here is link to complete error:
https://pastebin.com/DnM4xKSW

os: windows10pro, latest/gratest
hw: asus a15 (tuf)

best regards,

aum
s love nia

**Comment by ShadowJonathan** [comment]
Currently the correct wheels aren't uploaded to pypi, we're planning to at some point, but for the moment i recommend doing the following;
- Download [these artifacts](https://github.com/astrorigin/pyswisseph/suites/3306810524/artifacts/77343196) (they're for `2.08.00-1`, which is what flatlib uses rn)
- Unzip them. This can be anywhere (even amongst other files in your download folder), just note down the exact path of where.
- When installing flatlib, add the following flag; `--find-links`, and then add that path.
- Pip should find the right files to install, and not try to compile pyswisseph for you.

**Comment by aum7** [comment]
ok, i have irc'd pyswisseph author and pyswisseph pypi maintainer, we solved the issue, i guess pypi will be updated somewhere soon, the error should be resolved for windows users.

lol, jonathan was faster than me, a second or two

have fun,

aum
s love nia

edit: if you are not really well versed with coding, here is what you should write, in command line:
pip install flatlib --find-links "D:\dev\temp"
replace "D:\dev\temp" with "path\to\your\folder" where unziped files are

**Comment by adrifcarvalho** [comment]
> Currently the correct wheels aren't uploaded to pypi, we're planning to at some point, but for the moment i recommend doing the following;
> 
> * Download [these artifacts](https://github.com/astrorigin/pyswisseph/suites/3306810524/artifacts/77343196) (they're for `2.08.00-1`, which is what flatlib uses rn)
> * Unzip them. This can be anywhere (even amongst other files in your download folder), just note down the exact path of where.
> * When installing flatlib, add the following flag; `--find-links`, and then add that path.
> * Pip should find the right files to install, and not try to compile pyswisseph for you.

Good night! These page is not working now! Where am I found this now?
