### ISSUE TITLE
SwissEph file 'seas_18.se1' not found in PATH '.:/users/ephe2/:/users/ephe/'

### ISSUE THREAD

**Issue by Jordi588** [flatangle/flatlib#66]
I'm trying to create a chart object with `IDs=const.LIST_OBJECTS` parameter like: 
`chart = Chart(date, pos, IDs=const.LIST_OBJECTS)`

It doesn't work, giving:

`Exception Type: Error`
`Exception Value: SwissEph file 'seas_18.se1' not found in PATH '.:/users/ephe2/:/users/ephe/'`

But the file `seas_18.se1` is located at flatlib/resources.

Any idea? Is that a bug?

With for example:
`chart = Chart(date, pos, IDs=const.LIST_OBJECTS_TRADITIONAL)`
or
`chart = Chart(date, pos, IDs=const.LIST_SEVEN_PLANETS)`

it is indeed working

**Comment by jminutaglio** [comment]
I'm also getting the same error.

I've never seen this in flatlib-0.2.1, seems like something introduced w/ the flatlib-0.2.3 release.  :/

**Comment by MichealSBingham** [comment]
Having the same issue... any fix? @jminutaglio

**Comment by Jordi588** [comment]
I fixed it with
```
import swisseph as swe
swe.set_ephe_path('/usr/local/lib/python3.8/site-packages/flatlib/resources/swefiles')
chart = Chart(date, pos, IDs=const.LIST_OBJECTS, hsys=const.HOUSES_PLACIDUS)
```

Note that the path is derived from my docker environment, probably you will need to fix with your path files

**Comment by joaoventura** [comment]
I hate to say this, but "it works on my computer"! There are lots of memes for that...

![](http://www.quickmeme.com/img/76/76305c0677aa65f0eac8af9ad80fe946c26e4001d25078ef448f02903abaaf82.jpg)

**Comment by frederichoule** [comment]
I have the same problem when using flatlib in a Google Cloud Function. @Jordi588 fix doesn't work in that context. Any tips?

**Comment by jminutaglio** [comment]
@frederichoule - also was unable to get the @Jordi588 fix to work in GCF.

A workaround is to get the client to retry the call upon detecting the error.  I get the error 'often' but a retry of the same will give the expected return.  (or a couple retries).  

flatlib-0.2.1 did not have this issue, but I haven't been able to 'go back' - will not currently compile with needed dependencies. 

Hope that helps....

**Comment by frederichoule** [comment]
I found how to do it @jminutaglio 

[Here](https://github.com/astrorigin/swisseph/blob/master/sweph.c#L1368) you can see that environment variable SE_EPHE_PATH has priority, so if you deploy your GCF using the `--set-env-vars SE_EPHE_PATH=/layers/google.python.pip/pip/lib/python3.9/site-packages/flatlib/resources/swefiles` parameter, it works right away.

**Comment by jminutaglio** [comment]
@frederichoule  - ty. So that 'fixes' the `seas_18.se1` error?

**Comment by frederichoule** [comment]
Exactly.
- `flatlib` uses [pyswisseph](https://github.com/astrorigin/pyswisseph)
- `pyswisseph` uses [swisseph](https://github.com/astrorigin/swisseph)
- `swisseph` uses the `SE_EPHE_PATH` prior to any path passed with `set_ephe_path()`
- `seas_18.se1` is located in `.../flatlib/resources/swefiles`, so we just need to find the exact path of the library on the system, and pass it as the `SE_EPHE_PATH` environment variable.

**Comment by jminutaglio** [comment]
@frederichoule - TY so much for posting this!  :)

**Comment by webstylejordi** [comment]
Hola Jordi588 , tinc exactament el mateix problema. Estic en python 3.11 , has aconseguit arreglar-ho ?

**Comment by lunart888** [comment]
to auto find the path **seas_18.se1** with **flatlib** module
`import flatlib
import os
import swisseph as swe
pflat = os.path.join(flatlib.PATH_RES,'swefiles')

swe.set_sid_mode(swe.SIDM_LAHIRI)

swe.set_ephe_path(pflat)

jd = swe.julday(2024, 11, 30)

xjuno, retjuno= swe.calc_ut(jd,swe.JUNO)`
print(xjuno)
