### ISSUE TITLE
Plans to add planets past Saturn?

### ISSUE THREAD

**Issue by mateuszmp** [flatangle/flatlib#68]
Hi, do the project maintainers have plans to add Uranus and Neptune?

**Comment by joaoventura** [comment]
Do you have some source code to illustrate the error you got?

**Comment by mateuszmp** [comment]
```
from flatlib import const
from flatlib.chart import Chart
from flatlib.datetime import Datetime
from flatlib.geopos import GeoPos

date = Datetime('2021/12/04', '12:00', '+01:00')
pos = GeoPos('50n00', '20e00')
chart = Chart(date, pos)
uranus = chart.get(const.URANUS)
```
errors out and prints:
```
~\miniconda3\envs\ml\lib\site-packages\flatlib\chart.py in get(self, ID)
     90             return self.getAngle(ID)
     91         else:
---> 92             return self.getObject(ID)
     93 
     94 

~\miniconda3\envs\ml\lib\site-packages\flatlib\chart.py in getObject(self, ID)
     70     def getObject(self, ID):
     71         """ Returns an object from the chart. """
---> 72         return self.objects.get(ID)
     73 
     74     def getHouse(self, ID):

~\miniconda3\envs\ml\lib\site-packages\flatlib\lists.py in get(self, ID)
     42     def get(self, ID):
     43         """ Retrieves an object from this list. """
---> 44         return self.content[ID]
     45 
     46     def copy(self):

KeyError: 'Uranus'
```

**Comment by joaoventura** [comment]
Flatlib is a traditional astrology library, so by default it returns only the traditional set of planets. To use non-traditional planets, you have to do:

`chart = Chart(date, pos, IDs=const.LIST_OBJECTS)`

Then you can access all objects on that list (https://github.com/flatangle/flatlib/blob/master/flatlib/const.py#L256)

**Comment by MichealSBingham** [comment]
@joaoventura , I get the error error: 'SwissEph file \'seas_18.se1\' not found in PATH now if I use 

`chart = Chart(date, pos, IDs=const.LIST_OBJECTS)
`

Any fix?

**Comment by acmpo6ou** [comment]
Be sure to use `IDs` as parameter name, and not `ids`. It's case sensitive.
