### ISSUE TITLE
House calculation

### ISSUE THREAD

**Issue by generalsvr** [flatangle/flatlib#69]
I have a problem with house calculation. Here is code example:

`date = Datetime('1930/01/01', '10:00', '+00:00')
pos = GeoPos("55N45","37E36") 
chart = Chart(date, pos, hsys='Placidus', IDs=const.LIST_OBJECTS)
sun = chart.get(const.SUN)
sunhouse = chart.houses.getObjectHouse(sun)
print(sunhouse)
`

The result is `<House9 Capricorn +01:01:35 15.506900746302676>`

I tried a lot of different services, here is what they show:

![Screenshot from 2021-12-27 13-33-40](https://user-images.githubusercontent.com/32482126/147463728-d1094335-adc4-45aa-bc9c-3e84a52d2833.png)
![Screenshot from 2021-12-27 13-32-19](https://user-images.githubusercontent.com/32482126/147463738-e5bd4523-5d0a-41c8-9c4d-5c42b27fe741.png)

Everywhere hsys == Placidus. Can you tell me why the results are different?

**Comment by joaoventura** [comment]
Do you want the cusp of the house where the Sun is in, or do you want to know the position the sun is?
I've just tested it, if you do `print(sun)` you'll get those 10º16 Capricorn (Position of the sun in capricorn)...
But if you print the house by doing `print(sunhouse)`, it'll print 01º01 Capricorn which is the position of the House 9 cusp..

Do you know the difference between a planet and an astrology house?
