### ISSUE TITLE
Is there a way to calculate lunation day?

### ISSUE THREAD

**Issue by unrealfuzzy** [flatangle/flatlib#71]
Hi, I'm trying to figure out how to get a lunar day for a given date-time.
I'm referring to Lunar Calendar with 29-30 days a phase.
I see there's a way to calculate moon phase (4 quarters) but I'm trying to get the lunar day number.

**Comment by joaoventura** [comment]
Hi, Github Issues should be used for reporting errors in the software and things like that, not for requesting help! Nevertheless, my suggestion for you would be to find the last New Moon, get its date, and then compute how many days have passed. [This piece of code](https://github.com/flatangle/flatlib/blob/master/flatlib/ephem/tools.py#L55) shows how to find the last new/full moon (to compute the syzygy), so you just need to reuse it to suit your needs. Basically, set `offset = 0` in line 66 to find the previous new moon..
