### ISSUE TITLE
Results don't match with other pages' results

### ISSUE THREAD

**Issue by molnaredom** [flatangle/flatlib#73]
- Hi, I really like your code, but every time I try to compute an ASC , it does not matches with other pages results. 
- I used this code:
```
date = Datetime('2001/01/01', '01:01', '+01:00')
pos = GeoPos('47n11', '20w12') # HUN Szolnok
chart = Chart(date, pos, hsys='Placidus',IDs=const.LIST_OBJECTS)

obj = chart.get(const.HOUSE1)
print(obj)
```
- The result is: `<House1 Virgo +23:08:31 24.066321625075204>`

- I used the same parameters, but in other pages I always get a different result:

[https://horoscopes.astro-seek.com/calculate-house-systems/?send_calculation=1&narozeni_den=1&narozeni_mesic=1&narozeni_rok=2001&narozeni_hodina=01&narozeni_minuta=01&narozeni_city=Szolnok%2C+Hungary&narozeni_mesto_hidden=Szolnok&narozeni_stat_hidden=HU&narozeni_podstat_kratky_hidden=&narozeni_podstat_hidden=J%C3%A1sz-Nagykun-Szolnok&narozeni_input_hidden=&narozeni_podstat2_kratky_hidden=&narozeni_podstat3_kratky_hidden=&narozeni_sirka_stupne=47&narozeni_sirka_minuty=11&narozeni_sirka_smer=0&narozeni_delka_stupne=20&narozeni_delka_minuty=12&narozeni_delka_smer=0&narozeni_timezone_form=auto&narozeni_timezone_dst_form=auto&house_system=placidus&house_system2=whole&house_system3=koch&house_system4=equal&hid_fortune=1&hid_fortune_check=on&hid_vertex=1&hid_vertex_check=on&hid_chiron=1&hid_chiron_check=on&hid_lilith=1&hid_lilith_check=on&hid_uzel=1&hid_uzel_check=on](url)

![Screenshot 2022-02-20 at 18-12-06 House System Calculator, Compare your Birth Chart in Multiple House Systems Astro-Seek com](https://user-images.githubusercontent.com/77636185/154855416-13859cda-bd46-4068-8836-f6368d6751a9.png)

![Screenshot 2022-02-20 at 18-11-12 House System Calculator, Compare your Birth Chart in Multiple House Systems Astro-Seek com](https://user-images.githubusercontent.com/77636185/154855425-2258f8c8-015c-4112-8d9e-52dea68a0904.png)

I am not sure with the time zones, but I tried all of them and it didn't work.

How could I get the same results?

**Comment by MichealSBingham** [comment]
I've run into this same problem. Did you find a solution/explanation? 

It's because the tz dataset can be unreliable for dates before 1970 and I also found that if you use dates out of the country it sometimes has this bug. 

@molnaredom

**Comment by MichealSBingham** [comment]
I ran into the problem with Bill Clinton's ascendant

**Comment by molnaredom** [comment]
> I've run into this same problem. Did you find a solution/explanation? 
> 
> It's because the tz dataset can be unreliable for dates before 1970 and I also found that if you use dates out of the country it sometimes has this bug. 
> 
> @molnaredom 

I didn't found any solution for this issue.
I tried to use an other repo for getting asrology datas. I can recommend @ryuphi 's astrology-api: https://github.com/ryuphi/astrology-api
(it is in JS but you can use it with the api)

**Comment by MichealSBingham** [comment]
Thank you!

**Comment by joaoventura** [comment]
@molnaredom, according to your coordinates (47n11, 20w12), is Hungary now in the middle of the Atlantic Ocean? 
Because Google Maps says Hungary is in continental Europe! 

If I use the **correct coordinates** (47n11, 20e12 - please note the "e" as in East, instead of "w" as in West) , it gives me the correct result..

```python
date = Datetime('2001/01/01', '01:01', '+01:00')
pos = GeoPos('47n11', '20e12')  # HUN Szolnok
chart = Chart(date, pos, hsys='Placidus', IDs=const.LIST_OBJECTS)

obj = chart.get(const.HOUSE1)
print(obj)
```

`>>> <House1 Libra +23:04:43 27.034772788243203>`

For all future viewers: please double/triple check your input data before opening an issue!

**Comment by molnaredom** [comment]
Thank you very much for your answer. 
I checked it for one week, very much times, but for some reason I did not find this solution.
