### ISSUE TITLE
add new planet to flatlib objects

### ISSUE THREAD

**Issue by dave-sdt** [flatangle/flatlib#76]
i need to add Ceres (dwarf planet) and get its position and other infos. is there any function or way to add new planet that didn't exist in flatlib cont objects?

**Comment by velkyvont** [comment]
It is easy. In **ephem/swe.py** find `SWE_OBJECTS` and add `const.CERES: 17,` into the list.

In **const.py** add `CERES = 'Ceres'` into Names and `CERES` into `LIST_OBJECTS`

**Comment by dave-sdt** [comment]
> It is easy. In **ephem/swe.py** find `SWE_OBJECTS` and add `const.CERES: 17,` into the list.
> 
> In **const.py** add `CERES = 'Ceres'` into Names and `CERES` into `LIST_OBJECTS`

Thanks a lot. How about Eris? I tried to find Eris with other planetary numbers instead of 17 but could not find it.

**Comment by velkyvont** [comment]
Eris is not a planet but an asteroid. I don't think Flatlib currently supports asteroids. But you should be able to get the object directly from pyswisseph. This may require downloading additional ephimeris files.

**Comment by horvathr967** [comment]
Is it possible to add the Vertex to the Object or the House list? If not, do you know a way to calculate it based on other data?

**Comment by joaoventura** [comment]
This is a traditional astrology library. Vertex is not part of the traditional set of planets..
