### ISSUE TITLE
iterating through const.LIST_OBJECTS with chart.get() throws error at uranus

### ISSUE THREAD

**Issue by aum7** [flatangle/flatlib#78]
hi
thx for sharing
as a newbie, i was going through flatlib readthedocs, and wrote simple script, which gave me an error
using linux mint 20.3
with original python 3.8
installed flatlib with pip3 install flatlib
which also installed pyswisseph 2.8...
script:
`
from flatlib.datetime import Datetime
from flatlib.geopos import GeoPos
from flatlib.chart import Chart
from flatlib import const

date = Datetime('2022/07/20', '20:03', '+00:00')
pos = GeoPos('19n26', '99w10')  # mexico city
chart = Chart(date, pos)
for l in const.LIST_OBJECTS:
    print(chart.get(l))
`
error:
`
x@susaMint:~/Documents/vscode$ python3 flatangle-test.py 
<Sun Cancer +28:05:17 +00:57:16>
<Moon Taurus +00:52:37 +12:34:21>
<Mercury Leo +02:44:16 +02:04:28>
<Venus Cancer +03:20:43 +01:12:29>
<Mars Taurus +10:42:26 +00:40:20>
<Jupiter Aries +08:36:42 +00:01:35>
<Saturn Aquarius +23:40:05 -00:03:48>
Traceback (most recent call last):
  File "flatangle-test.py", line 17, in <module>
    print(chart.get(l))
  File "/home/aumhren/.local/lib/python3.8/site-packages/flatlib/chart.py", line 92, in get
    return self.getObject(ID)
  File "/home/aumhren/.local/lib/python3.8/site-packages/flatlib/chart.py", line 72, in getObject
    return self.objects.get(ID)
  File "/home/aumhren/.local/lib/python3.8/site-packages/flatlib/lists.py", line 44, in get
    return self.content[ID]
KeyError: 'Uranus'
`
not sure what is going on here
if this is expected behavior aka you can not reproduce, please excuse my french, and ignore the bug report

have fun
aum
s love nia

**Comment by joaoventura** [comment]
Just saw this now. By default flatlib computes the chart for the seven traditional astrology planets. Inside the chart you can find the list of objects (planets). You can iterate over that list..
