### ISSUE TITLE
Retrieving angle value 

### ISSUE THREAD

**Issue by Pretorian29** [flatangle/flatlib#81]
Hello, probably this may be simple but I am stuck trying to retieve the angle value from <Asc Capricorn +00:10:58>,
is there any example how to retrieve the elements individually like: 'Asc',  'Capricorn', '+00:10:58'?
I can find a function inside asc = chart.getAngle(const.ASC) to get the value of the angle.
I will be very gratefull for any help.
Thank you.

**Comment by joaoventura** [comment]
Houses, Fixed Stars and planets are all subclasses of GenericObject (https://github.com/flatangle/flatlib/blob/master/flatlib/object.py#L22). Therefore you have access to all properties and methods of the GenericObject class. So you can do things like `asc.lon`, `asc.sign`, `asc.antiscia()`, etc.

**Comment by Pretorian29** [comment]
Hello and thank you for your reply. I managed to get the results I wanted using asc.lon, I thing my confusion is to think as a spanish native speaker... using longitude worked as the value to display the angle lines in the radius of the chartwheel.
thank you very much for your work, I am creating a beautiful chart thanks to your library.
