### ISSUE TITLE
Replacing swisseph with skyfield

### ISSUE THREAD

**Issue by aduchon** [flatangle/flatlib#83]
Has anyone tried replacing swisseph with skyfield for a completely free version? https://github.com/skyfielders/python-skyfield

**Comment by joaoventura** [comment]
It seems skyfield is a library geared towards astronomy, so it would be lots of work to replicate what the swiss ephemeris provides regarding astrology. Also, it seems quite heavy as it depends on numpy, which must be quite some megabytes of dependency. The C sweph library is very small in comparison.
So, it makes no sense to consider that skyfield package for this project..
