### ISSUE TITLE
Find an exact time of an aspect

### ISSUE THREAD

**Issue by marekhewelt** [flatangle/flatlib#9]
First of all, thank you João for making this an open source project.
Sorry if I miss something. Is there a way of finding a date and time of an astrological event such as exact aspects or sign ingress?

Many thanks,
Mark

**Comment by joaoventura** [comment]
Hi Mark, I do not have anything like that in this library, but you can try to implement something like I did for finding the date of prev/next solar returns: https://github.com/flatangle/flatlib/blob/master/flatlib/ephem/tools.py#L75
